Repository sparc-software-hust/fmecg-web-server, pull requests merged in 2024-11, with the labels that each got.

#596 t20241#30 Feature/api get schedule doctor
  server_ecg20241/src/app.module.ts
  server_ecg20241/src/modules/consultation_schedule/consultation_schedule.module.ts
  server_ecg20241/src/modules/schedule/schedule.controller.ts
  server_ecg20241/src/modules/schedule/schedule.repository.ts
  server_ecg20241/src/modules/schedule/schedule.service.ts
  server_ecg20241/src/modules/user/user.module.ts
  server_ecg20241/src/modules/user/user.service.ts
Labels: back-end

#595 t20241#36 feature/schedule_management_ui: show diagnosis; fix some errors in BE, FE and fix allow creating a diagnosis logic
  server_ecg20241/seeders/20241010090728-dummy-users.js
  server_ecg20241/seeders/20241011113850-dummy-devices.js
  server_ecg20241/seeders/20241011114006-dummy-schedules.js
  server_ecg20241/seeders/20241011114007-dummy-diagnosis.js
  server_ecg20241/seeders/20241011114111-dummy-consultation-schedule.js
  server_ecg20241/seeders/20241011114257-dummy-records.js
  server_ecg20241/src/modules/device/device.module.ts
  server_ecg20241/src/modules/device/device.service.ts
  server_ecg20241/src/modules/device_details/device_detail.module.ts
  server_ecg20241/src/modules/diagnosis/diagnosis.controller.ts
  server_ecg20241/src/modules/diagnosis/diagnosis.repository.ts
  server_ecg20241/src/modules/diagnosis/diagnosis.service.ts
  server_ecg20241/src/modules/diagnosis/dto/diagnosis.response.ts
  server_ecg20241/src/modules/schedule/schedule.service.ts
  ui_web/src/api/api-generated.ts
  ui_web/src/components/Modal/ModalControlData.tsx
  ui_web/src/components/Modal/ModalDiagnosisData.tsx
  ui_web/src/components/Modal/ModalShowDiagnosis.tsx
  ui_web/src/components/Modal/ScheduleModal.tsx
  ui_web/src/pages/schedule/schedule.tsx
  ui_web/src/redux/reducer/diagnosisSlice.ts
  ui_web/src/utils/dateUtils.ts
Labels: front-end, back-end

#598 t20241#39 feature/schedule_management_ui: disable busy dates, hours when creating next schedule date and fix some errors
  server_ecg20241/src/modules/schedule/dto/schedule.request.ts
  server_ecg20241/src/modules/schedule/schedule.controller.ts
  server_ecg20241/src/modules/schedule/schedule.service.ts
  server_ecg20241/src/modules/user/user.controller.ts
  ui_web/src/api/api-generated.ts
  ui_web/src/components/Modal/ModalDiagnosisData.tsx
  ui_web/src/pages/schedule/schedule.tsx
  ui_web/src/redux/reducer/scheduleSlice.ts
  ui_web/src/redux/reducer/userSlice.ts
Labels: front-end, back-end

#602 t20241#39 feature/schedule_management_ui: disable adding diagnosis and next schedule date if selected date is in the future
  identity_service/.env
  server_ecg20241/.env
  server_ecg20241/seeders/20241011114006-dummy-schedules.js
  server_ecg20241/seeders/20241011114111-dummy-consultation-schedule.js
  ui_web/bin/.env
  ui_web/src/components/Modal/ModalDiagnosisData.tsx
  ui_web/src/components/Modal/ScheduleModal.tsx
  ui_web/src/pages/schedule/schedule.tsx
Labels: front-end

#605 t20241#43 feature/schedule_management_ui: add schedule modal (doctor must be selected first)
  identity_service/src/module/authentication/authentication.service.ts
  server_ecg20241/src/modules/schedule/dto/schedule.request.ts
  server_ecg20241/src/modules/schedule/schedule.controller.ts
  server_ecg20241/src/modules/schedule/schedule.service.ts
  ui_web/bin/.env
  ui_web/src/api/api-generated.ts
  ui_web/src/components/Modal/ModalAddDiagnosis.tsx
  ui_web/src/components/Modal/ModalAddSchedule.tsx
  ui_web/src/pages/schedule/schedule.tsx
  ui_web/src/redux/reducer/scheduleSlice.ts
  ui_web/src/utils/dateUtils.ts
Labels: front-end

#610 t20241#45 feature/ui_authorization: set permissions for all pages
  server/src/modules/device/device.controller.ts
  server/src/modules/record/record.controller.ts
  server/src/modules/record/record.repository.ts
  server/src/modules/record/record.service.ts
  server/src/modules/schedule/schedule.controller.ts
  server/src/modules/schedule/schedule.module.ts
  server/src/modules/schedule/schedule.service.ts
  server/src/modules/user/user.controller.ts
  server/src/modules/user/user.module.ts
  server/src/modules/user/user.service.ts
  ui_web/src/api/api-generated.ts
  ui_web/src/components/Modal/ModalShowDiagnosis.tsx
  ui_web/src/components/Modal/ScheduleModal.tsx
  ui_web/src/components/Table/dataTable.tsx
  ui_web/src/layouts/routes.type.ts
  ui_web/src/pages/device/device.tsx
  ui_web/src/pages/record/record.tsx
  ui_web/src/pages/schedule/schedule.tsx
  ui_web/src/pages/user/user.tsx
  ui_web/src/redux/reducer/deviceSlice.ts
  ui_web/src/redux/reducer/diagnosisSlice.ts
  ui_web/src/redux/reducer/recordSlice.ts
  ui_web/src/redux/reducer/scheduleSlice.ts
  ui_web/src/redux/reducer/userSlice.ts
Labels: front-end, back-end

#611 t20241 improve(back-end): add get schedule of doctor by doctor_id with role …
  server/src/modules/schedule/schedule.controller.ts
Labels: back-end

#613 t20241#42 feature/notification: add notification to all pages
  server/src/modules/authentication/authentication.guard.ts
  ui_web/src/api/api-generated.ts
  ui_web/src/components/Modal/ModalAddDiagnosis.tsx
  ui_web/src/components/Modal/ModalAddSchWithDoctor.tsx
  ui_web/src/components/Modal/ModalShowDiagnosis.tsx
  ui_web/src/components/notification.ts
  ui_web/src/pages/device/device.details.tsx
  ui_web/src/pages/device/device.tsx
  ui_web/src/pages/record/record.tsx
  ui_web/src/pages/schedule/schedule.tsx
  ui_web/src/pages/user/user.details.tsx
  ui_web/src/pages/user/user.tsx
  ui_web/src/redux/reducer/deviceSlice.ts
  ui_web/src/redux/reducer/diagnosisSlice.ts
  ui_web/src/redux/reducer/recordSlice.ts
  ui_web/src/redux/reducer/scheduleSlice.ts
  ui_web/src/redux/reducer/userSlice.ts
Labels: front-end, back-end

#618 t20241#48 feature(back-end): create notification module
  server/seeders/20241011113719-dummy-schedule-status.js
  server/src/entities/notification_schedule.model.ts
  server/src/modules/notification/dto/notification.request.ts
  server/src/modules/notification/dto/notification.response.ts
  server/src/modules/notification/interfaces/notifcation.controller.ts
  server/src/modules/notification/interfaces/notification,module.ts
  server/src/modules/notification/interfaces/notification.repository.ts
  server/src/modules/notification/interfaces/notification.service.ts
Labels: back-end

#616 t20241#46 feature/schedule: function for doctors to accept or reject a patient's schedule
  server/src/modules/consultation_schedule/consultation_schedule.repository.ts
  server/src/modules/consultation_schedule/consultation_schedule.service.ts
  server/src/modules/schedule/dto/acceptSchedule.request.ts
  server/src/modules/schedule/schedule.controller.ts
  server/src/modules/schedule/schedule.repository.ts
  server/src/modules/schedule/schedule.service.ts
  ui_web/src/api/api-generated.ts
  ui_web/src/components/Modal/ScheduleModal.tsx
  ui_web/src/constants/index.ts
  ui_web/src/pages/schedule/schedule.tsx
  ui_web/src/redux/reducer/scheduleSlice.ts
Labels: front-end, back-end
