Repository sparc-software-hust/fmecg-web-server, pull requests merged in 2024-12, with the labels that each got.

#620 t20241#51 feature/account_info: add account detail page
  server/src/modules/user/user.controller.ts
  server/src/modules/user/user.service.ts
  ui_web/src/api/api-generated.ts
  ui_web/src/assets/avatar.svg
  ui_web/src/assets/logo.png
  ui_web/src/layouts/header.scss
  ui_web/src/layouts/header.tsx
  ui_web/src/layouts/routes.tsx
  ui_web/src/layouts/routes.type.ts
  ui_web/src/pages/account/account.details.scss
  ui_web/src/pages/account/account.details.tsx
  ui_web/src/pages/account/index.ts
  ui_web/src/pages/user/user.details.tsx
  ui_web/src/redux/reducer/userSlice.ts
Labels: front-end, back-end

#621 t20241#53 improve/home_page
  server/src/app.module.ts
  server/src/modules/device/device.repository.ts
  server/src/modules/device/device.service.ts
  server/src/modules/record/record.repository.ts
  server/src/modules/record/record.service.ts
  server/src/modules/statistic/dto/statistic.response.ts
  server/src/modules/statistic/statistic.controller.ts
  server/src/modules/statistic/statistic.module.ts
  server/src/modules/statistic/statistic.service.ts
  server/src/modules/user/user.repository.ts
  server/src/modules/user/user.service.ts
  ui_web/package.json
  ui_web/src/api/api-generated.ts
  ui_web/src/api/index.ts
  ui_web/src/components/Chart/EChart.tsx
  ui_web/src/components/Chart/LineChart.tsx
  ui_web/src/components/Chart/chart.scss
  ui_web/src/components/Chart/configs/eChart.tsx
  ui_web/src/components/Chart/configs/lineChart.tsx
  ui_web/src/layouts/header.tsx
  ui_web/src/layouts/nav.scss
  ui_web/src/layouts/notification.tsx
  ui_web/src/layouts/routes.tsx
  ui_web/src/pages/home/home.scss
  ui_web/src/pages/home/home.tsx
  ui_web/src/redux/reducer/statisticSlice.ts
  ui_web/src/redux/store.ts
Labels: front-end, back-end

#624 t20241#56 feature/filter and search; improve backend: add search and filter on columns, implement transaction
  server/src/modules/consultation_schedule/consultation_schedule.repository.ts
  server/src/modules/consultation_schedule/consultation_schedule.service.ts
  server/src/modules/consultation_schedule/dto/consultation_schedule.request.ts
  server/src/modules/schedule/schedule.controller.ts
  server/src/modules/schedule/schedule.module.ts
  server/src/modules/schedule/schedule.repository.ts
  server/src/modules/schedule/schedule.service.ts
  server/src/modules/transaction/transaction.module.ts
  server/src/modules/transaction/transaction.service.ts
  server/src/modules/user/user.repository.ts
  ui_web/package.json
  ui_web/src/components/Drawer/Drawer.tsx
  ui_web/src/components/Table/dataTable.tsx
  ui_web/src/constants/index.ts
  ui_web/src/layouts/notification.tsx
  ui_web/src/pages/device/device.tsx
  ui_web/src/pages/record/record.tsx
  ui_web/src/pages/user/user.tsx
Labels: back-end

#629 t20241#58 Improve/schedule: check existing schedule
  server/src/modules/notification/notifcation.controller.ts
  server/src/modules/notification/notification.module.ts
  server/src/modules/notification/notification.repository.ts
  server/src/modules/notification/notification.service.ts
  server/src/modules/schedule/schedule.controller.ts
  server/src/modules/schedule/schedule.module.ts
  server/src/modules/schedule/schedule.repository.ts
  server/src/modules/schedule/schedule.service.ts
  ui_web/src/layouts/notification.tsx
Labels: front-end, back-end

#638 t20241#63 improve/schedule: add cron job to auto check schedules and add reason when doctor rejecting a schedule
  server/migrations/20241009098937-create-notifications-schedule.js
  server/package.json
  server/seeders/20241124100854-dummy-notifications-schedule.js
  server/src/entities/availability_schedule.ts
  server/src/entities/notification_schedule.model.ts
  server/src/index.ts
  server/src/modules/consultation_schedule/consultation_schedule.repository.ts
  server/src/modules/consultation_schedule/consultation_schedule.service.ts
  server/src/modules/notification/dto/notification.request.ts
  server/src/modules/notification/dto/notification.response.ts
  server/src/modules/notification/notification.module.ts
  server/src/modules/notification/notification.repository.ts
  server/src/modules/schedule/dto/schedule.response.ts
  server/src/modules/schedule/schedule.controller.ts
  server/src/modules/schedule/schedule.module.ts
  server/src/modules/schedule/schedule.repository.ts
  server/src/modules/schedule/schedule.service.ts
  ui_web/src/api/api-generated.ts
  ui_web/src/assets/groupAvatar.svg
  ui_web/src/components/Modal/ModalAddSchWithTime.tsx
  ui_web/src/components/Modal/ModalShowDiagnosis.tsx
  ui_web/src/components/Modal/ScheduleModal.tsx
  ui_web/src/layouts/notification.tsx
  ui_web/src/pages/chat/chat.scss
  ui_web/src/pages/chat/chat.tsx
  ui_web/src/pages/schedule/schedule.tsx
  ui_web/src/redux/reducer/scheduleSlice.ts
  ui_web/src/utils/dateUtils.ts
Labels: front-end, back-end

#640 feature(back-end): add save form data with file url for record
  package.json
  server/package.json
  server/seeders/20241011114257-dummy-records.js
  server/src/modules/record/record.controller.ts
  server/src/modules/record/record.service.ts
Labels: back-end

#646 fix(mobile): error when build
  mobile_app/android/app/build/python/proguard-rules.pro
  mobile_app/android/build.gradle
  mobile_app/lib/screens/bluetooth_screens/ble_chart_test.dart
  mobile_app/lib/screens/personal_infor_screens/personal_infor_screens.dart
  mobile_app/pubspec.yaml
Labels: mobile

#647 improve(mobile): update gradle new version flutter
  mobile_app/android/app/build.gradle
  mobile_app/android/build.gradle
  mobile_app/android/gradle/wrapper/gradle-wrapper.properties
  mobile_app/android/settings.gradle
  mobile_app/lib/controllers/firebase_messages_controller.dart
  mobile_app/lib/providers/auth_provider.dart
  mobile_app/lib/screens/history_screens/bluetooth_classic_data_exchange_screen.dart
  mobile_app/lib/screens/history_screens/bluetooth_classic_discovery_screen.dart
  mobile_app/lib/screens/history_screens/bluetooth_classic_screen.dart
  mobile_app/pubspec.yaml
Labels: mobile
