Repository sparc-software-hust/fmecg-web-server, pull requests merged in 2024-02, with the labels that each got.

#125 improve(mobile): update analysis to format code
  mobile_app/analysis_options.yaml
  mobile_app/lib/AllText.dart
  mobile_app/lib/components/circular_avatar.dart
  mobile_app/lib/components/live_chart.dart
  mobile_app/lib/constants/theme.dart
  mobile_app/lib/controllers/auth_controller.dart
  mobile_app/lib/controllers/ecg_data_controller.dart
  mobile_app/lib/controllers/firebase_messages_controller.dart
  mobile_app/lib/main.dart
  mobile_app/lib/models/doctor_info.dart
  mobile_app/lib/screens/auth_screens/login1_screen.dart
  mobile_app/lib/screens/auth_screens/register_screen.dart
  mobile_app/lib/screens/bluetooth_screens/ble_chart_test.dart
  mobile_app/lib/screens/bluetooth_screens/ble_scanning_screen.dart
  mobile_app/lib/screens/bluetooth_screens/ble_screen.dart
  mobile_app/lib/screens/bluetooth_screens/bluetooth_off_screen.dart
  mobile_app/lib/screens/chat_screens/chat_detail_screen.dart
  mobile_app/lib/screens/doctor_screens/doctor_detail.dart
  mobile_app/lib/screens/history_screens/history_record_chart.dart
  mobile_app/lib/screens/history_screens/history_screen.dart
  mobile_app/lib/screens/home_screen.dart
  mobile_app/lib/screens/login_screen/sign_up_screen.dart
  mobile_app/lib/screens/main_screen.dart
  mobile_app/lib/screens/news_screens/news_all_screens.dart
  mobile_app/lib/screens/news_screens/news_reference.dart
  mobile_app/lib/screens/user_screens/user_profile_screen.dart
  mobile_app/lib/utils/error_handling.dart
  mobile_app/lib/utils/utils.dart
Labels: mobile

#128 improve(mobile): cicd update
  .github/workflows/main.yml
Labels: mobile

#130 improve(mobile): update cicd triggered only when merged
  .github/workflows/main.yml
Labels: mobile

#133 feature(front-end): create base web frontend #36
  frontend_web/.gitignore
  frontend_web/package.json
  frontend_web/public/favicon.ico
  frontend_web/public/index.html
  frontend_web/public/logo192.png
  frontend_web/public/logo512.png
  frontend_web/public/manifest.json
  frontend_web/public/robots.txt
  frontend_web/src/App.css
  frontend_web/src/App.js
  frontend_web/src/App.test.js
  frontend_web/src/api/common.api.js
  frontend_web/src/assets/icons/avatar.svg
  frontend_web/src/components/Button.js
  frontend_web/src/components/MenuBar/menubar.js
  frontend_web/src/components/Modal/ModalCreate/ModalCreateCourse.js
  frontend_web/src/components/Modal/ModalDelete.js
  frontend_web/src/components/Modal/ModalEdit/ModalEdit.js
  frontend_web/src/components/Modal/ModalEdit/ModalEditChapter.js
  frontend_web/src/components/Modal/ModalEdit/ModalEditCourse.js
  frontend_web/src/components/Modal/ModalEdit/ModalEditQuestion.js
  frontend_web/src/components/Modal/ModalEdit/ModalEditSection.js
  frontend_web/src/components/Modal/ModalEdit/ModalEditUser.js
  frontend_web/src/components/Modal/ModalQuestion.js
  frontend_web/src/components/Notification.js
  frontend_web/src/components/Table/dataTable.js
  frontend_web/src/configs/config.js
  frontend_web/src/configs/store.js
  frontend_web/src/index.css
  frontend_web/src/index.js
  frontend_web/src/layouts/AuthProvider/index.js
  frontend_web/src/layouts/DefaultLayout/DefaultLayout.css
  frontend_web/src/layouts/DefaultLayout/DefaultLayout.js
  frontend_web/src/layouts/Header/header.css
  frontend_web/src/layouts/Header/header.js
  frontend_web/src/layouts/Sidebar/sidebar.js
  frontend_web/src/logo.svg
  frontend_web/src/models/manage.table.js
  frontend_web/src/models/table/user.table.js
  frontend_web/src/pages/Account/Detail.js
  frontend_web/src/pages/Home/home.js
  frontend_web/src/pages/Home/home.scss
  frontend_web/src/pages/Login/Login.js
  frontend_web/src/pages/Login/login.scss
  frontend_web/src/pages/NotFound/notfound.js
  frontend_web/src/pages/User/CreateUser.js
  frontend_web/src/redux/reducer/userSlice.js
  frontend_web/src/redux/store.js
  frontend_web/src/reportWebVitals.js
  frontend_web/src/routes/route.js
  frontend_web/src/setupTests.js
  frontend_web/src/styles/style.sass
  frontend_web/src/utils/axios.js
  frontend_web/src/utils/handleApiRequest.js
  frontend_web/src/utils/renderQuestion.js
  frontend_web/src/utils/storageUtils.js
Labels: web/server

#138 Feature/GitHub actions ci cd mobile
  .github/workflows/auto_create_pull_request.yaml
  .github/workflows/build.yml
  .github/workflows/main.yml
Labels: mobile, automerge

#139 Feature/GitHub actions ci cd mobile
  .github/workflows/main.yml
Labels: mobile, automerge

#140 Feature/GitHub actions ci cd mobile
  .github/workflows/main.yml
Labels: mobile, automerge
