Repository sparc-software-hust/fmecg-web-server, pull requests merged in 2024-10, with the labels that each got.

#521 imprve(mobile): update cache
  mobile_app/README.md
  mobile_app/android/.gitignore
  mobile_app/android/app/google-services.json
Labels: mobile

#530 t20241#7 improve(front-end): update landing page
  old-fmecg/frontend_web/landing-page/css/owl.carousel.min.css
  old-fmecg/frontend_web/landing-page/css/style.css
  old-fmecg/frontend_web/landing-page/img/fmECG/React.webp
  old-fmecg/frontend_web/landing-page/img/fmECG/aws.png
  old-fmecg/frontend_web/landing-page/img/fmECG/flutter.png
  old-fmecg/frontend_web/landing-page/img/fmECG/mongodb.png
  old-fmecg/frontend_web/landing-page/img/fmECG/nodejs.png
  old-fmecg/frontend_web/landing-page/img/fmECG/postgresql.png
  old-fmecg/frontend_web/landing-page/index.html
Labels: front-end

#560 improve(mobile): check google services not need to be secret
  mobile_app/android/.gitignore
  mobile_app/android/app/google-services.json
Labels: mobile

#561 improve(front-end): convert data landing page to js file
  old-fmecg/frontend_web/landing-page/constants/data.js
  old-fmecg/frontend_web/landing-page/index.html
Labels: front-end

#569 t20241 fix(back-end): add plainToInstance
  ECG_20241/server/src/modules/device/device.controller.ts
Labels: back-end

#570 t20241#22 feature(front-end): add user information table & add, edit, delete button
  ECG_20241/server/src/index.ts
  ECG_20241/server/src/modules/record/record.controller.ts
  ECG_20241/server/src/modules/user/user.controller.ts
  ui_web/src/api/api-generated.ts
  ui_web/src/api/index.ts
  ui_web/src/components/Table/dataTable.scss
  ui_web/src/components/Table/dataTable.tsx
  ui_web/src/constraints/index.ts
  ui_web/src/pages/user/user.tsx
  ui_web/src/redux/store.ts
  ui_web/src/redux/userSlice.ts
  ui_web/src/utils/arrayUtils.ts
Labels: front-end, back-end

#571 t20241#5 device_manangement: improve get all devices API, add device information table
  ECG_20241/server/src/modules/device/device.controller.ts
  ECG_20241/server/src/modules/device/device.module.ts
  ECG_20241/server/src/modules/device/device.service.ts
  ECG_20241/server/src/modules/device/dto/device.response.ts
  ECG_20241/server/src/modules/user/user.module.ts
  ECG_20241/server/src/modules/user/user.repository.ts
  ECG_20241/server/src/modules/user/user.service.ts
  ui_web/src/api/index.ts
  ui_web/src/components/Table/dataTable.tsx
  ui_web/src/layouts/routes.tsx
  ui_web/src/layouts/routes.type.ts
  ui_web/src/pages/device/device.tsx
  ui_web/src/pages/device/index.ts
  ui_web/src/redux/deviceSlice.ts
  ui_web/src/redux/store.ts
Labels: front-end, back-end

#582 t20241#27 feature/device_management_ui: add create, update, delete function to device management, show device details on row click and CUD details when editing a device
  ECG_20241/server/migrations/20241003092312-create-device-details.js
  ECG_20241/server/seeders/20241010090728-dummy-users.js
  ECG_20241/server/seeders/20241011113640-dummy-device-type.js
  ECG_20241/server/seeders/20241011113850-dummy-devices.js
  ECG_20241/server/seeders/20241011114034-dummy-device-schedule.js
  ECG_20241/server/seeders/20241011114257-dummy-records.js
  ECG_20241/server/seeders/20241011114311-dummy-device-details.js
  ECG_20241/server/src/entities/device_detail.model.ts
  ECG_20241/server/src/modules/device/device.controller.ts
  ECG_20241/server/src/modules/device/device.module.ts
  ECG_20241/server/src/modules/device/device.repository.ts
  ECG_20241/server/src/modules/device/device.service.ts
  ECG_20241/server/src/modules/device/dto/device.request.ts
  ECG_20241/server/src/modules/device/dto/device.response.ts
  ECG_20241/server/src/modules/device_details/device_detail.controller.ts
  ECG_20241/server/src/modules/device_details/device_detail.module.ts
  ECG_20241/server/src/modules/device_details/device_detail.repository.ts
  ECG_20241/server/src/modules/device_details/device_detail.service.ts
  ECG_20241/server/src/modules/device_details/dto/device_detail.request.ts
  ECG_20241/server/src/modules/device_details/dto/device_detail.response.ts
  ECG_20241/server/src/modules/user/user.controller.ts
  ECG_20241/server/src/modules/user/user.repository.ts
  ECG_20241/server/src/modules/user/user.service.ts
  ui_web/src/api/api-generated.ts
  ui_web/src/api/index.ts
  ui_web/src/components/Modal/ModalControlData.tsx
  ui_web/src/constants/index.ts
  ui_web/src/constraints/index.ts
  ui_web/src/layouts/nav.tsx
  ui_web/src/pages/device/device.details.tsx
  ui_web/src/pages/device/device.tsx
  ui_web/src/pages/user/user.details.tsx
  ui_web/src/pages/user/user.tsx
  ui_web/src/redux/reducer/deviceSlice.ts
  ui_web/src/redux/reducer/userSlice.ts
  ui_web/src/utils/arrayUtils.ts
Labels: front-end, back-end

#584 t20241#32 feature/schedule_management_UI: show calendar, show schedule when clicking in a day
  ECG_20241/server/seeders/20241011113719-dummy-schedule-status.js
  ECG_20241/server/seeders/20241011114006-dummy-schedules.js
  ECG_20241/server/seeders/20241011114007-dummy-diagnosis.js
  ECG_20241/server/seeders/20241011114034-dummy-device-schedule.js
  ECG_20241/server/seeders/20241011114111-dummy-consultation-schedule.js
  ECG_20241/server/seeders/20241011114257-dummy-records.js
  ECG_20241/server/src/modules/consultation_schedule/consultation_schedule.repository.ts
  ECG_20241/server/src/modules/consultation_schedule/consultation_schedule.service.ts
  ECG_20241/server/src/modules/schedule/dto/schedule.response.ts
  ECG_20241/server/src/modules/schedule/schedule.service.ts
  ui_web/src/api/api-generated.ts
  ui_web/src/api/index.ts
  ui_web/src/components/Modal/ScheduleModal.tsx
  ui_web/src/components/Modal/schedule.scss
  ui_web/src/constants/index.ts
  ui_web/src/layouts/nav.tsx
  ui_web/src/layouts/routes.tsx
  ui_web/src/layouts/routes.type.ts
  ui_web/src/pages/schedule/index.tsx
  ui_web/src/pages/schedule/schedule.tsx
  ui_web/src/redux/reducer/scheduleSlice.ts
  ui_web/src/redux/store.ts
  ui_web/src/utils/dateUtils.ts
Labels: front-end

#588 t20241#33 feature/schedule_management_UI: add diagnosis and next schedule date by doctor (not authorized user yet)
  ECG_20241/server/migrations/20241003070211-create-consultation-schedule.js
  ECG_20241/server/src/entities/consultation_schedule.model.ts
  ECG_20241/server/src/modules/consultation_schedule/consultation_schedule.controller.ts
  ECG_20241/server/src/modules/consultation_schedule/consultation_schedule.module.ts
  ECG_20241/server/src/modules/consultation_schedule/consultation_schedule.repository.ts
  ECG_20241/server/src/modules/consultation_schedule/consultation_schedule.service.ts
  ECG_20241/server/src/modules/consultation_schedule/dto/consultation_schedule.request.ts
  ECG_20241/server/src/modules/consultation_schedule/dto/consultation_schedule.response.ts
  ECG_20241/server/src/modules/diagnosis/diagnosis.controller.ts
  ECG_20241/server/src/modules/diagnosis/diagnosis.module.ts
  ECG_20241/server/src/modules/diagnosis/diagnosis.repository.ts
  ECG_20241/server/src/modules/diagnosis/diagnosis.service.ts
  ECG_20241/server/src/modules/diagnosis/dto/diagnosis.request.ts
  ECG_20241/server/src/modules/schedule/dto/schedule.request.ts
  ECG_20241/server/src/modules/schedule/schedule.controller.ts
  ECG_20241/server/src/modules/schedule/schedule.module.ts
  ECG_20241/server/src/modules/schedule/schedule.repository.ts
  ECG_20241/server/src/modules/schedule/schedule.service.ts
  ECG_20241/server/src/modules/user/user.repository.ts
  ECG_20241/server/src/modules/user/user.service.ts
  mobile_app/lib/screens/main_screen.dart
  mobile_app/lib/screens/new_screens/additional_item.dart
  mobile_app/lib/screens/new_screens/chat_screen.dart
  mobile_app/lib/screens/new_screens/circular_indicator_home.dart
  mobile_app/lib/screens/new_screens/home_screen.dart
  mobile_app/lib/screens/new_screens/progress_home.dart
  mobile_app/lib/screens/new_screens/schedule_screen.dart
  mobile_app/lib/screens/new_screens/search_screen.dart
  mobile_app/lib/screens/new_screens/setting_screen.dart
  ui_web/src/api/api-generated.ts
  ui_web/src/api/index.ts
  ui_web/src/components/Modal/ModalDiagnosisData.tsx
  ui_web/src/components/Modal/ScheduleModal.tsx
  ui_web/src/components/Modal/schedule.scss
  ui_web/src/constants/index.ts
  ui_web/src/pages/schedule/schedule.tsx
  ui_web/src/redux/reducer/diagnosisSlice.ts
  ui_web/src/redux/reducer/scheduleSlice.ts
  ui_web/src/redux/store.ts
Labels: front-end, back-end
