Repository sparc-software-hust/fmecg-web-server, pull requests merged in 2025-01, with the labels that each got.

#645 Feature/new feature app mobile
  mobile_app/lib/app.dart
  mobile_app/lib/networks/api_setup.dart
  mobile_app/lib/networks/http_dio.dart
  mobile_app/lib/providers/auth_provider.dart
  mobile_app/lib/screens/login_screen/log_in_screen.dart
  mobile_app/lib/screens/main_screen.dart
  mobile_app/lib/screens/new_screens/home_screen.dart
  mobile_app/lib/screens/new_screens/schedule_screen.dart
  mobile_app/lib/screens/new_screens/search_screen.dart
  mobile_app/lib/screens/notification_screens/notification_screen.dart
  mobile_app/lib/screens/personal_infor_screens/personal_infor_screens.dart
  mobile_app/lib/screens/schedule_appointments_screens/date_picker_screens.dart
  mobile_app/lib/screens/schedule_appointments_screens/doctor_list_screens.dart
  mobile_app/lib/screens/schedule_appointments_screens/schedule_appointments.dart
  mobile_app/lib/utils/utils.dart
  mobile_app/pubspec.yaml
Labels: mobile

#658 feature/device_assignment
  server/migrations/20241003092233-create-devices.js
  server/migrations/20241003092336-create-records.js
  server/migrations/20241003106042-create-device-schedule.js
  server/package.json
  server/seeders/20241011113650-dummy-device-status.js
  server/seeders/20241011113850-dummy-devices.js
  server/seeders/20241011114034-dummy-device-schedule.js
  server/seeders/20241011114257-dummy-records.js
  server/src/app.module.ts
  server/src/entities/device.model.ts
  server/src/entities/device_schedule.model.ts
  server/src/entities/record.model.ts
  server/src/entities/schedule.model.ts
  server/src/main.ts
  server/src/modules/consultation_schedule/consultation_schedule.service.ts
  server/src/modules/device/device.controller.ts
  server/src/modules/device/device.module.ts
  server/src/modules/device/device.repository.ts
  server/src/modules/device/device.service.ts
  server/src/modules/device/dto/device.request.ts
  server/src/modules/device/dto/device.response.ts
  server/src/modules/device/interfaces/device.service.interface.ts
  server/src/modules/record/dto/record.request.ts
  server/src/modules/record/dto/record.response.ts
  server/src/modules/record/record.module.ts
  server/src/modules/record/record.repository.ts
  server/src/modules/record/record.service.ts
  server/src/modules/schedule/schedule.controller.ts
  server/src/modules/schedule/schedule.module.ts
  server/src/modules/schedule/schedule.service.ts
  server/src/modules/user/user.controller.ts
  ui_web/src/api/api-generated.ts
  ui_web/src/components/Modal/ModalAssignDevice.tsx
  ui_web/src/components/Modal/ModalControlData.tsx
  ui_web/src/components/Table/dataTable.tsx
  ui_web/src/constants/index.ts
  ui_web/src/layouts/routes.type.ts
  ui_web/src/pages/device/device.details.tsx
  ui_web/src/pages/device/device.tsx
  ui_web/src/pages/record/record.details.tsx
  ui_web/src/pages/record/record.tsx
  ui_web/src/redux/reducer/deviceSlice.ts
Labels: front-end, back-end

#661 feature/record_chart: add configuration for record chart
  server/src/modules/record/record.service.ts
  ui_web/package.json
  ui_web/src/components/LineChart/LineChart.tsx
  ui_web/src/components/Modal/ModalAddDiagnosis.tsx
  ui_web/src/components/Modal/ModalChart.tsx
  ui_web/src/components/Modal/ScheduleModal.tsx
  ui_web/src/components/Table/dataTable.tsx
  ui_web/src/pages/record/record.tsx
  ui_web/src/pages/schedule/schedule.tsx
  ui_web/src/pages/user/user.details.tsx
  ui_web/src/redux/reducer/recordSlice.ts
Labels: front-end

#663 improve/account_detail: improve ui
  ui_web/src/components/Table/dataTable.tsx
  ui_web/src/pages/account/account.details.scss
  ui_web/src/pages/account/account.details.tsx
Labels: front-end
